import json
from typing import Union
from pathlib import Path

from data_io.collect_data import timetables_request

APIKEY = "96bc1c08-5f6e-411e-a69a-bdbff719bc7e"


def test_keys_in_stops_coord(apikey: str=APIKEY, f_path: Union[None, str] = None):
    """It tests in keys in stops coordinates (wspolrzedne przystankow) are as they should be. If Warsaw buses change their
    names or their order it will throw an error.
    If f_path parameter is given, than it reads data from file. Else, it request data from website"""

    if f_path is None:
        stops_coord = timetables_request(action="stops_coord")
    else:
        with open(f_path) as file:
            stops_coord = json.load(file)
    # for i, row in enumerate(stops_coord):
    #     row = row["values"]
    #     print(row[0])
    #     if i >5:
    #         break
    for row in stops_coord:
        row = row["values"]
        assert row[0]["key"] == "zespol"
        assert row[1]["key"] == "slupek"
        assert row[2]["key"] == "nazwa_zespolu"
        assert row[3]["key"] == "id_ulicy"
        assert row[4]["key"] == "szer_geo"
        assert row[5]["key"] == "dlug_geo"
        assert row[6]["key"] == "kierunek"
        assert row[7]["key"] == "obowiazuje_od"

def correct_timetables(dir_to_timetables: str):
    """It goes through all of the timetables generated by collect_data.timetables_collect_all() and it checks if
    every first element of the file is a dictionary. Is yes, I ASSUME that that the data were correctly downloaded."""

    count_errors = 0

    files = Path(dir_to_timetables)
    for i, file in enumerate(files.iterdir()):
        print(file.name)
        if i > 100:
            break



if __name__ == "__main__":
    test_keys_in_stops_coord(f_path = ".\\test_dir4\\stops_coord.json")
